### ISSUE TITLE
feature proposals

### ISSUE THREAD

**Issue by freder** [baincd/vscode-markdown-color-plus#1]
![Screenshot-2021-08-04-at-13 36 23](https://user-images.githubusercontent.com/724844/128175291-7d469c0f-333c-441c-bc53-e20099079c2c.jpg)

**Comment by baincd** [comment]
These are both really good ideas.  I'll look into them when I find time.  

Thank you for the feedback!  I'm glad you like this extension. 🙂

**Comment by baincd** [comment]
I have added support for horizontal rules and blockquotes to the latest version (1.5.0).  I'd love to hear if you have any feedback. 

Thank you again for the idea!
