### ISSUE TITLE
selection color in code block

### ISSUE THREAD

**Issue by changsijay** [baincd/vscode-markdown-color-plus#2]
I've set background for `markdown-color-plus.fencedCodeBlock.background.darkThemeColor`.
When I try to copy the content of fenced code block, because the background didn't changed to selection color,
it is not easy to see what range i selected.

Could we set different background color when selected in code block?

**Comment by baincd** [comment]
Unfortunately, that is the behavior of VS Code when setting background color on text in a text editor.  I've noticed the same behavior in other extensions ([Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight)) that also set the background color on text in text editors.

To my knowledge, there is no option available through the VS Code API to allow setting the selection color.  However, there is a workaround - reduce the opacity of the background color.

This can be done by [setting the alpha channel](https://www.w3schools.com/css/css3_colors.asp) (which controls how transparent/opaque the color is) on the background color.  When the background color is more transparent (less opaque), the selected text highlight is easier to see.

This can be defined using either of the following formats:
- `#RRGGBBAA` (ex: `#0A0A0A66` → the "66" is the Alpha channel in hex.  "FF" is 100% opaque, "00" is 100% transparent, 66 is approx 25% opaque)
- `rgba(r,g,b,a)` (ex: `rgba(10,10,10,0.25)` → 0.25 is the opacity on a scale of 0.0-1.0

**Comment by changsijay** [comment]
@baincd thanks a lot, after set 
`"markdown-color-plus.fencedCodeBlock.background.darkThemeColor": "#3B3C3766",`
looks pretty good now

this workaround works fine for me, I am closing this ticket.

**Comment by baincd** [comment]
In v1.5.0, I added a note to the README to clarify this for other users as well.

([ae8b8f7](https://github.com/baincd/vscode-markdown-color-plus/commit/ae8b8f7b775d83fc39f55ddd343aa4615c95904a))
